import type { IResolvedStyle } from "./types";

/** 1Shot default branding (shadcn nova / neutral tokens). */
export const DEFAULT_STYLE: IResolvedStyle = {
  theme: {
    primary: "#2499a9",
    primaryForeground: "#ffffff",
    background: "oklch(1 0 0)",
    foreground: "oklch(0.145 0 0)",
    muted: "oklch(0.97 0 0)",
    mutedForeground: "oklch(0.556 0 0)",
    border: "oklch(0.922 0 0)",
    accent: "oklch(0.97 0 0)",
    accentForeground: "oklch(0.205 0 0)",
    radius: "0.625rem",
    fontSans: "'Geist Variable', ui-sans-serif, system-ui, sans-serif",
  },
  features: {
    hideCloseBox: false,
    disableCredentials: false,
    disableDelegations: false,
    allowedChains: null,
  },
  copy: {
    productName: "1Shot Wallet",
    tagline:
      "Permissionless Embedded Wallet.\nSecurely log in with passkeys or start fresh.",
    logoUrl: "",
    account: {
      selectNetworkTitle: "Select network",
      selectNetworkCancelLabel: "Cancel",
      copyAddressLabel: "Copy address",
      addressCopiedLabel: "Address copied",
      addressCopyFailedLabel: "Copy failed",
    },
    connect: {
      title: "Connect wallet",
      body: "The connected app is requesting your wallet address. You may be asked to verify with your passkey after you continue.",
      rejectLabel: "Reject",
      continueLabel: "Continue",
    },
    walletSetup: {
      title: "Set up your wallet",
      body: "This wallet uses a passkey to secure your keys on this device. Log in with an existing passkey or create a new account before continuing.",
      cancelLabel: "Cancel",
      loginLabel: "Login with passkey ->",
      createLabel: "Create account",
    },
    passkeyName: {
      title: "Name your passkey",
      body: "Choose a name for this wallet passkey. Your device will use it when you create the credential and when you sign in later.",
      fieldLabel: "Account name",
      placeholder: "e.g. My wallet",
      emptyError: "Enter a name for your passkey.",
      termsAcceptancePrefix: "I agree to the",
      termsOfServiceLabel: "Terms of Service",
      termsAcceptanceJoiner: "and",
      privacyPolicyLabel: "Privacy Policy",
      termsAcceptanceError:
        "Accept the Terms of Service and Privacy Policy to continue.",
      termsOfServiceUrl: "https://1shotapi.com/terms-of-service",
      privacyPolicyUrl: "https://1shotapi.com/privacy-policy",
      cancelLabel: "Cancel",
      continueLabel: "Continue",
    },
    personalSign: {
      title: "Sign message",
      accountLabel: "Account",
      messageLabel: "Message",
      rejectLabel: "Reject",
      signLabel: "Sign",
    },
    siwe: {
      title: "Sign-in request",
      body: "A site wants you to sign in by proving you own this account. This will not spend tokens or change on-chain balances.",
      estimatedChangesLabel: "Estimated changes",
      noChangesLabel: "No changes",
      networkLabel: "Network",
      requestFromLabel: "Request from",
      signingInWithLabel: "Signing in with",
      messageLabel: "Message",
      uriLabel: "URI",
      rejectLabel: "Cancel",
      signLabel: "Confirm",
      signingHint: "Confirm in the signing panel…",
    },
    typedData: {
      title: "Sign typed data",
      accountLabel: "Account",
      primaryTypeLabel: "Primary type",
      domainLabel: "Domain",
      messageLabel: "Message",
      rejectLabel: "Reject",
      signLabel: "Sign",
    },
    sendTransaction: {
      title: "Send transaction",
      accountLabel: "Account",
      contractLabel: "Contract",
      contractCreationLabel: "(contract creation)",
      valueLabel: "Value",
      dataLabel: "Data",
      chainLabel: "Chain",
      rejectLabel: "Reject",
      signLabel: "Sign",
    },
    confirmTransfer: {
      title: "Confirm transfer",
      body: "{domain} is requesting to send tokens from your wallet. Review the amount and recipient before confirming.",
      amountLabel: "Amount",
      tokenLabel: "Token",
      receiverLabel: "To",
      chainLabel: "Network",
      rejectLabel: "Reject",
      confirmLabel: "Confirm",
    },
    transferTokens: {
      title: "Send",
      body: "Enter the recipient and amount to send.",
      amountLabel: "Amount",
      amountPlaceholder: "0.0",
      recipientLabel: "Recipient",
      recipientPlaceholder: "0x… or name.eth",
      scanQrLabel: "Scan QR",
      cancelLabel: "Cancel",
      sendLabel: "Send",
      invalidAmountError: "Enter a valid amount.",
      insufficientBalanceError: "Insufficient balance.",
      invalidAddressError: "Enter a valid address or ENS name.",
      sendFailedError: "Send failed.",
      sentTitle: "Transaction sent",
      sentBody: "Your transfer has been submitted to the network.",
      hashLabel: "Transaction hash",
      copyHashLabel: "Copy hash",
      hashCopiedLabel: "Copied",
      hashCopyFailedLabel: "Copy failed",
      viewOnExplorerLabel: "View on explorer",
      doneLabel: "Done",
    },
    grantExecutionPermission: {
      title: "Grant spending permission",
      body: "{domain} wants a periodic ERC-20 spending permission for {to} on {chainName}.",
      hostLabel: "App",
      toLabel: "Delegate",
      chainLabel: "Network",
      permissionTypeLabel: "Permission",
      tokenLabel: "Token",
      periodAmountLabel: "Amount per period",
      periodAmountPlaceholder: "0.0",
      periodDurationLabel: "Period duration (seconds)",
      periodDurationPlaceholder: "86400",
      periodDurationHint: "How often the allowance resets (e.g. 86400 = 1 day).",
      startLabel: "Start (Unix seconds, optional)",
      memoLabel: "Memo",
      memoPlaceholder: "Note for your records",
      invalidAmountError: "Enter a valid period amount.",
      invalidDurationError: "Enter a period duration of at least 1 second.",
      rejectLabel: "Reject",
      grantLabel: "Grant",
    },
    cancelDelegation: {
      title: "Cancel permission",
      body: "Cancel this spending permission on {chainName}? This submits an on-chain transaction and requires a small fee.",
      hostLabel: "App",
      chainLabel: "Network",
      rejectLabel: "Keep",
      confirmLabel: "Cancel permission",
    },
    passkeyPrompt: {
      unlock: {
        title: "Unlock with passkey",
        body: "Confirm with your passkey to unlock this wallet.",
      },
      create: {
        title: "Create passkey",
        body: "Follow the device prompts to create a passkey and unlock this wallet. You may be asked to confirm twice.",
      },
      sign: {
        title: "Sign with passkey",
        body: "Confirm with your passkey to approve this signature.",
      },
      encrypt: {
        title: "Encrypt with passkey",
        body: "Confirm with your passkey to encrypt data for secure storage.",
      },
      decrypt: {
        title: "Decrypt with passkey",
        body: "Confirm with your passkey to decrypt stored wallet data.",
      },
      relayerAuth: {
        title: "Authenticate with passkey",
        body: "Confirm with your passkey to authenticate with the 1Shot Relayer.",
      },
      walletUpgrade: {
        title: "Authorize upgrading your wallet",
        body: "Confirm with your passkey for a one-time network upgrade so the 1Shot Relayer can submit gas-abstracted transactions for you.",
      },
      approveTransaction: {
        title: "Approve transaction",
        body: "Confirm with your passkey to authorize this transaction for the 1Shot Relayer.",
      },
      adjustFee: {
        title: "Confirm fee update",
        body: "Confirm with your passkey to authorize the updated relayer fee for this transaction.",
      },
      backup: {
        title: "Confirm backup",
        body: "Confirm with your passkey to create an encrypted recovery backup.",
      },
      exportPrivateKey: {
        title: "Export private key",
        body: "Confirm with your passkey to reveal your private key.",
      },
    },
    credentialOffer: {
      title: "Accept credential offer?",
      body: "{issuerName} ({issuerId}) wants to issue a credential to your wallet.",
      offeredHeading: "Offered credentials:",
      passkeyNote:
        "You may be asked to verify with your passkey after you continue.",
      rejectLabel: "Reject",
      acceptLabel: "Accept",
    },
    credentialPresentation: {
      title: "Share credential?",
      body: "{verifierName} ({verifierId}) is requesting proof.",
      credentialDetail:
        "Credential: {credentialType} from {credentialIssuer}",
      claimsHeading: "Claims to disclose:",
      passkeyNote:
        "You may be asked to verify with your passkey after you continue.",
      rejectLabel: "Reject",
      shareLabel: "Share",
    },
    credentials: {
      tabLabel: "Credentials",
      emptyCountLabel: "No credentials stored yet.",
      countLabel: "{count} credential(s)",
      refreshLabel: "Refresh",
      loadingBody: "Loading…",
      emptyBody:
        "Accept an offer or refresh from the relayer to sync credentials.",
      loadFailedError: "Failed to load credentials",
      refreshFailedError: "Failed to refresh from relayer",
      notFoundError: "Credential not found in local cache.",
      openFailedError: "Failed to open credential",
      typeColumn: "Type",
      issuerColumn: "Issuer",
      issuedColumn: "Issued",
      viewLabel: "View",
      detailFallbackTitle: "Credential",
      detailDescription: "Full credential details and claims.",
      issuerLabel: "Issuer",
      formatLabel: "Format",
      issuedLabel: "Issued",
      validUntilLabel: "Valid until",
      idLabel: "Id",
      claimsHeading: "Claims",
      claimsLoading: "Loading claims…",
      claimsEmpty: "No claims.",
      closeLabel: "Close",
    },
    delegations: {
      tabLabel: "Delegations",
      emptyCountLabel: "No spending permissions yet.",
      countLabel: "{count} permission(s)",
      refreshLabel: "Refresh",
      loadingBody: "Loading…",
      emptyBody:
        "Permissions granted to apps appear here. Refresh to sync from the vault.",
      loadFailedError: "Failed to load permissions",
      refreshFailedError: "Failed to refresh from relayer",
      cancelFailedError: "Failed to cancel permission",
      notFoundError: "Permission not found in local cache.",
      cancelLabel: "Cancel",
      noMemoLabel: "No memo",
      periodSummary: "{amount} {symbol} every {duration}",
      permissionSummary: "{permissionType} → {to}",
    },
    balances: {
      tabLabel: "Balances",
      emptyCountLabel: "No assets tracked yet.",
      countLabel: "{count} asset(s)",
      addLabel: "Add asset",
      refreshLabel: "Refresh",
      loadingBody: "Loading…",
      emptyBody:
        "Add an asset yourself or accept a host addAsset request to start tracking balances.",
      loadFailedError: "Failed to load tracked assets",
      refreshFailedError: "Failed to refresh balances",
      addFailedError: "Failed to add asset",
      invalidAddressError: "Enter a valid 0x address.",
      assetColumn: "Asset",
      chainColumn: "Chain",
      balanceColumn: "Balance",
      viewLabel: "View",
      closeLabel: "Close",
      addDialogTitle: "Add asset",
      addDialogBody:
        "Track an ERC-20 (or other) contract on the currently selected network.",
      addressLabel: "Contract address",
      addressPlaceholder: "0x…",
      addDialogCancelLabel: "Cancel",
      addDialogSubmitLabel: "Add",
      addConfirmTitle: "Add asset",
      addConfirmBody:
        "The connected app is requesting to add a custom token to your wallet for tracking. Please verify the contract details before proceeding.",
      addConfirmWarning:
        "Anyone can create a token. Make sure you trust this source before adding it to your portfolio.",
      addConfirmRejectLabel: "Reject",
      addConfirmAcceptLabel: "Add",
      balanceUnavailable: "—",
      balanceNonErc20: "—",
      receiveLabel: "Receive",
      receiveTitle: "Receive",
      receiveBody: "Scan this QR code or copy your {chainLabel} address.",
      receiveAddressLabel: "Address",
      receiveQrAlt: "{chainLabel} wallet address",
      receiveCopyLabel: "Copy address",
      receiveCopiedLabel: "Address copied",
      receiveCopyFailedLabel: "Copy failed",
      receiveCloseLabel: "Close",
      sendLabel: "Send",
    },
    exportPrivateKey: {
      title: "Export private key",
      body: "Anyone with this private key can control your wallet and move your funds.\n\nOnly continue if you understand the risk. Store the key in a password manager or import it into a trusted external wallet — never share it, and never paste it into a website or chat.",
      continueLabel: "Export key",
      cancelLabel: "Cancel",
      closeLabel: "Close",
      revealingBody:
        "Confirm with your passkey, then copy the key from the secure panel and click Done.",
      cancelledError: "Passkey prompt was cancelled or blocked.",
      failedError: "Could not export private key.",
    },
    importPrivateKey: {
      title: "Import private key",
      body: "Paste a secp256k1 private key to unlock this wallet for this browser tab only. The key never leaves the secure signing panel.\n\nPrefer a passkey when you can — imported keys are not stored after you close this tab.",
      continueLabel: "Import key",
      cancelLabel: "Cancel",
      closeLabel: "Close",
      importingBody:
        "Enter your private key in the secure panel, then confirm.",
      cancelledError: "Import was cancelled.",
      invalidKeyError: "That does not look like a valid private key.",
      failedError: "Could not import private key.",
    },
    advancedOptions: {
      title: "Advanced options",
      menuLabel: "Advanced options",
      onboardingLabel: "Advanced options",
      body: "Import or export your private key, or switch to a different passkey account.",
      exportLabel: "Export private key",
      importLabel: "Import private key",
      changeAccountLabel: "Change account",
      closeLabel: "Close",
    },
  },
  dark: false,
};
