import type { IResolvedStyle } from "./types";

/** 1Shot default branding (shadcn nova / neutral tokens). */
export const DEFAULT_STYLE: IResolvedStyle = {
  theme: {
    primary: "#2499a9",
    primaryForeground: "#ffffff",
    background: "oklch(1 0 0)",
    foreground: "oklch(0.145 0 0)",
    muted: "oklch(0.97 0 0)",
    mutedForeground: "oklch(0.556 0 0)",
    border: "oklch(0.922 0 0)",
    accent: "oklch(0.97 0 0)",
    accentForeground: "oklch(0.205 0 0)",
    radius: "0.625rem",
    fontSans: "'Geist Variable', ui-sans-serif, system-ui, sans-serif",
  },
  copy: {
    productName: "1Shot Wallet",
    tagline:
      "Permissionless Embedded Wallet.\nSecurely log in with passkeys or start fresh.",
    logoUrl: "",
    connect: {
      title: "Connect wallet",
      body: "The connected app is requesting your wallet address. You may be asked to verify with your passkey after you continue.",
      rejectLabel: "Reject",
      continueLabel: "Continue",
    },
    walletSetup: {
      title: "Set up your wallet",
      body: "This wallet uses a passkey to secure your keys on this device. Log in with an existing passkey or create a new account before continuing.",
      cancelLabel: "Cancel",
      loginLabel: "Login with passkey ->",
      createLabel: "Create account",
    },
    passkeyName: {
      title: "Name your passkey",
      body: "Choose a name for this wallet passkey. Your device will use it when you create the credential and when you sign in later.",
      fieldLabel: "Account name",
      placeholder: "e.g. My wallet",
      emptyError: "Enter a name for your passkey.",
      cancelLabel: "Cancel",
      continueLabel: "Continue",
    },
    personalSign: {
      title: "Sign message",
      accountLabel: "Account",
      messageLabel: "Message",
      rejectLabel: "Reject",
      signLabel: "Sign",
    },
    typedData: {
      title: "Sign typed data",
      accountLabel: "Account",
      primaryTypeLabel: "Primary type",
      domainLabel: "Domain",
      messageLabel: "Message",
      rejectLabel: "Reject",
      signLabel: "Sign",
    },
    sendTransaction: {
      title: "Send transaction",
      accountLabel: "Account",
      contractLabel: "Contract",
      contractCreationLabel: "(contract creation)",
      valueLabel: "Value",
      dataLabel: "Data",
      chainLabel: "Chain",
      rejectLabel: "Reject",
      signLabel: "Sign",
    },
    credentialOffer: {
      title: "Accept credential offer?",
      body: "{issuerName} ({issuerId}) wants to issue a credential to your wallet.",
      offeredHeading: "Offered credentials:",
      passkeyNote:
        "You may be asked to verify with your passkey after you continue.",
      rejectLabel: "Reject",
      acceptLabel: "Accept",
    },
    credentialPresentation: {
      title: "Share credential?",
      body: "{verifierName} ({verifierId}) is requesting proof.",
      credentialDetail:
        "Credential: {credentialType} from {credentialIssuer}",
      claimsHeading: "Claims to disclose:",
      passkeyNote:
        "You may be asked to verify with your passkey after you continue.",
      rejectLabel: "Reject",
      shareLabel: "Share",
    },
    credentials: {
      tabLabel: "Credentials",
      emptyCountLabel: "No credentials stored yet.",
      countLabel: "{count} credential(s)",
      refreshLabel: "Refresh",
      loadingBody: "Loading…",
      emptyBody:
        "Accept an offer or refresh from the relayer to sync credentials.",
      loadFailedError: "Failed to load credentials",
      refreshFailedError: "Failed to refresh from relayer",
      notFoundError: "Credential not found in local cache.",
      openFailedError: "Failed to open credential",
      typeColumn: "Type",
      issuerColumn: "Issuer",
      issuedColumn: "Issued",
      viewLabel: "View",
      detailFallbackTitle: "Credential",
      detailDescription: "Full credential details and claims.",
      issuerLabel: "Issuer",
      formatLabel: "Format",
      issuedLabel: "Issued",
      validUntilLabel: "Valid until",
      idLabel: "Id",
      claimsHeading: "Claims",
      claimsLoading: "Loading claims…",
      claimsEmpty: "No claims.",
      closeLabel: "Close",
    },
    balances: {
      tabLabel: "Balances",
      emptyCountLabel: "No assets tracked yet.",
      countLabel: "{count} asset(s)",
      addLabel: "Add asset",
      loadingBody: "Loading…",
      emptyBody:
        "Add an asset yourself or accept a host addAsset request to start tracking balances.",
      loadFailedError: "Failed to load tracked assets",
      addFailedError: "Failed to add asset",
      invalidAddressError: "Enter a valid 0x address.",
      assetColumn: "Asset",
      chainColumn: "Chain",
      balanceColumn: "Balance",
      viewLabel: "View",
      closeLabel: "Close",
      addDialogTitle: "Add asset",
      addDialogBody:
        "Track an ERC-20 (or other) contract on the currently selected network.",
      addressLabel: "Contract address",
      addressPlaceholder: "0x…",
      addDialogCancelLabel: "Cancel",
      addDialogSubmitLabel: "Add",
      addConfirmTitle: "Add asset?",
      addConfirmBody:
        "The connected app wants you to track {assetName} on {chainLabel}.",
      addConfirmRejectLabel: "Reject",
      addConfirmAcceptLabel: "Add",
      balanceUnavailable: "—",
      balanceNonErc20: "—",
      receiveLabel: "Receive",
      receiveTitle: "Receive",
      receiveBody: "Scan this QR code or copy your {chainLabel} address.",
      receiveAddressLabel: "Address",
      receiveQrAlt: "{chainLabel} wallet address",
      receiveCopyLabel: "Copy address",
      receiveCopiedLabel: "Address copied",
      receiveCopyFailedLabel: "Copy failed",
      receiveCloseLabel: "Close",
    },
    createBackup: {
      title: "Create backup",
      body: "Enter a passphrase of at least {minLength} characters to encrypt your private key. Store the backup somewhere safe — you will need it to restore your wallet.",
      passphrasePrompt: "Passphrase (min {minLength} characters)",
      continueLabel: "Continue",
      cancelLabel: "Cancel",
      closeLabel: "Close",
      copyLabel: "Copy",
      copiedLabel: "Copied",
      copyFailedLabel: "Copy failed",
      doneLabel: "Done",
      encryptedLabel: "Encrypted backup",
      passwordTooShortError: "Passphrase is too short. Try again.",
      cancelledError: "Passkey prompt was cancelled or blocked.",
      failedError: "Backup failed.",
    },
    restoreBackup: {
      title: "Restore backup",
      body: "Enter the passphrase you used when creating this backup to unlock your wallet.",
      passphraseLabel: "Backup passphrase",
      restoreLabel: "Restore",
      cancelLabel: "Cancel",
      closeLabel: "Close",
      doneLabel: "Done",
      successBody: "Wallet restored. You can sign until this tab is closed.",
      decryptFailedError:
        "Could not decrypt the backup. Check the passphrase and try again.",
      cancelledError: "Passkey prompt was cancelled or blocked.",
      failedError: "Restore failed.",
    },
  },
  dark: false,
};
